name: Deployar el sitio HTML en Github Pages

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que uses, si es diferente.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js y ejecutar pruebas
      - name: Setup Node.js and run tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test

      # Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # El directorio con tu contenido HTML
          allow_empty_commit: true  # Opcional, útil para evitar errores si no hay cambios

