name: Deploy HTML Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configuraci贸n de repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuraci贸n de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instalaci贸n de dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar pruebas unitarias
      - name: Run tests
        run: npm test

      # Construir el sitio si las pruebas son exitosas
      - name: Build site
        run: npm run build # Cambia esto si necesitas un paso de construcci贸n

      # Deploy en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Cambia este valor al directorio de salida de tu proyecto
